<?php

class ProductsTableSeeder extends Seeder {

	public function run()
	{
		Product::truncate();
        $data = 
        [
        	[
        		"category_id"=> 1,
        		"code"		=> 123,
                "name"     =>"VÒNG ĐÁ MĂT HÔ NÂU VÀNG",
                "size"   =>23,
                "material"=>"Đá",
        		"quantity"=>123,
        		"origin_price"	=> 121,
        		"new_price"	=> 120,
                "image_url"        =>"img/products/1/item-1.png",
                "description"        =>"Đá đẹp",
                "introduce"        =>"Đây là đá đẹp 1",
                "status"        =>1,
                "created_at"        =>date('Y-m-d : H-i-s'),
        	],
        	[
        		"category_id"=> 2,
        		"code"		=> 2222,
                "name"     =>"VÒNG ĐÁ NHAM THẠCH NÚI LƯẢ",
                "size"   =>23,
                "material"=>"Đá",
        		"quantity"=>123,
        		"origin_price"	=> 121,
        		"new_price"	=> 120,
                "image_url"        =>"img/products/2/item-2.png",
                "description"        =>"Đá đẹp",
                "introduce"        =>"Đây là đá đẹp 2",
                "status"        =>1,
                "created_at"        =>date('Y-m-d : H-i-s'),
        	],
        	[
        		"category_id"=> 3,
        		"code"		=> 333,
                "name"     =>"VÒNG ĐÁ THẠCH ANH TÍM",
                "size"   =>23,
                "material"=>"Đá",
        		"quantity"=>123,
        		"origin_price"	=> 121,
        		"new_price"	=> 120,
                "image_url"        =>"img/products/3/item-3.png",
                "description"        =>"Đá đẹp",
                "introduce"        =>"Đây là đá đẹp 3",
                "status"        =>1,
                "created_at"        =>date('Y-m-d : H-i-s'),
        	],
        	[
        		"category_id"=> 4,
        		"code"		=> 4444,
                "name"     =>"VÒNG ĐÁ THẠCH ANH HÔNG",
                "size"   =>23,
                "material"=>"Đá",
        		"quantity"=>123,
        		"origin_price"	=> 121,
        		"new_price"	=> 120,
                "image_url"        =>"img/products/4/item-4.png",
                "description"        =>"Đá đẹp",
                "introduce"        =>"Đây là đá đẹp 4",
                "status"        =>1,
                "created_at"        =>date('Y-m-d : H-i-s'),
        	],
        	[
        		"category_id"=> 5,
        		"code"		=> 5555,
                "name"     =>"VÒNG ĐÁ MĂT HÔ NÂU VÀNG 5",
                "size"   =>23,
                "material"=>"Đá",
        		"quantity"=>123,
        		"origin_price"	=> 121,
        		"new_price"	=> 120,
                "image_url"        =>"img/products/5/item-1.png",
                "description"        =>"Đá đẹp",
                "introduce"        =>"Đây là đá đẹp 5",
                "status"        =>1,
                "created_at"        =>date('Y-m-d : H-i-s'),
        	],
        	[
        		"category_id"=> 6,
        		"code"		=> 6666,
                "name"     =>"VÒNG ĐÁ NHAM THẠCH NÚI LƯẢ 6",
                "size"   =>23,
                "material"=>"Đá",
        		"quantity"=>123,
        		"origin_price"	=> 121,
        		"new_price"	=> 120,
                "image_url"        =>"img/products/6/item-2.png",
                "description"        =>"Đá đẹp",
                "introduce"        =>"Đây là đá đẹp 6",
                "status"        =>1,
                "created_at"        =>date('Y-m-d : H-i-s'),
        	],
        	[
        		"category_id"=> 7,
        		"code"		=> 7777,
                "name"     =>"VÒNG ĐÁ THẠCH ANH TÍM 7",
                "size"   =>23,
                "material"=>"Đá",
        		"quantity"=>123,
        		"origin_price"	=> 121,
        		"new_price"	=> 120,
                "image_url"        =>"img/products/7/item-3.png",
                "description"        =>"Đá đẹp",
                "introduce"        =>"Đây là đá đẹp 7",
                "status"        =>1,
                "created_at"        =>date('Y-m-d : H-i-s'),
        	],
        ];
        Product::insert($data);
		}
}