<?php

class ProductsTableSeeder extends Seeder {

	public function run()
	{
		Product::truncate();
        $data = 
        [
        	[
		"type_id"=> 1,
		"code"		=> 123,
                "name"     =>"VÒNG ĐÁ MĂT HÔ NÂU VÀNG",
                "name_seo"     => "vong-da-mat-ho-mau-vang ",
                "size"   =>23,
                "material"=>"Đá",
		"quantity"=>123,
                "origin_price"  => 200000,
		"new_price"	=> null,
                "image_url"        =>"img/products/1/item-1.png",
                "description"        =>"Đá đẹp",
                "introduce"        =>"Đây là đá đẹp 1",
                "status"        =>0,
                "created_at"        =>date('Y-m-d : H-i-s'),
        	],
        	[
		"type_id"=> 1,
		"code"		=> 2222,
                "name"     =>"VÒNG ĐÁ NHAM THẠCH NÚI LƯẢ",
                "name_seo"     =>"vong-da-nham-thach-nui-lua",
                "size"   =>23,
                "material"=>"Đá",
		"quantity"=>123,
		"origin_price"	=> 150000,
		"new_price"	=> null,
                "image_url"        =>"img/products/2/item-2.png",
                "description"        =>"Đá đẹp",
                "introduce"        =>"Đây là đá đẹp 2",
                "status"        =>0,
                "created_at"        =>date('Y-m-d : H-i-s'),
        	],
        	[
		"type_id"=> 2,
		"code"		=> 333,
                "name"     =>"VÒNG ĐÁ THẠCH ANH TÍM",
                "name_seo"     =>"vong-da-thach-anh-tim",
                "size"   =>23,
                "material"=>"Đá",
		"quantity"=>123,
		"origin_price"	=> 400000,
		"new_price"	=> null,
                "image_url"        =>"img/products/3/item-3.png",
                "description"        =>"Đá đẹp",
                "introduce"        =>"Đây là đá đẹp 3",
                "status"        =>0,
                "created_at"        =>date('Y-m-d : H-i-s'),
        	],
        	[
		"type_id"=> 3,
		"code"		=> 4444,
                "name"     =>"VÒNG ĐÁ THẠCH ANH HÔNG",
                "name_seo"     =>"vong-da-thach-anh-hong",
                "size"   =>23,
                "material"=>"Đá",
		"quantity"=>123,
		"origin_price"	=> 300000,
		"new_price"	=> null,
                "image_url"        =>"img/products/4/item-4.png",
                "description"        =>"Đá đẹp",
                "introduce"        =>"Đây là đá đẹp 4",
                "status"        =>0,
                "created_at"        =>date('Y-m-d : H-i-s'),
        	],
        	[
		"type_id"=> 4,
		"code"		=> 5555,
                "name"     =>"VÒNG ĐÁ MĂT HÔ NÂU VÀNG 5",
                "name_seo"     =>"vong-da-mat-ho-nau-vang-5",
                "size"   =>23,
                "material"=>"Đá",
		"quantity"=>123,
		"origin_price"	=> 500000,
		"new_price"	=> null,
                "image_url"        =>"img/products/5/item-1.png",
                "description"        =>"Đá đẹp",
                "introduce"        =>"Đây là đá đẹp 5",
                "status"        =>0,
                "created_at"        =>date('Y-m-d : H-i-s'),
        	],
        	[
		"type_id"=> 5,
		"code"		=> 6666,
                "name"     =>"VÒNG ĐÁ NHAM THẠCH NÚI LƯẢ 6",
                "name_seo"     =>"vong-da-nham-thach-nui-lua-6",
                "size"   =>23,
                "material"=>"Đá",
		"quantity"=>123,
		"origin_price"	=> 600000,
		"new_price"	=> null,
                "image_url"        =>"img/products/6/item-2.png",
                "description"        =>"Đá đẹp",
                "introduce"        =>"Đây là đá đẹp 6",
                "status"        =>0,
                "created_at"        =>date('Y-m-d : H-i-s'),
        	],
        	[
		"type_id"=> 5,
		"code"		=> 7777,
                "name"     =>"VÒNG ĐÁ THẠCH ANH TÍM 7",
                "name_seo"     =>"vong-da-thach-anh-tim-7",
                "size"   =>23,
                "material"=>"Đá",
		"quantity"=>123,
		"origin_price"	=> 800000,
		"new_price"	=> 650000,
                "image_url"        =>"img/products/7/item-3.png",
                "description"        =>"Đá đẹp",
                "introduce"        =>"Đây là đá đẹp 7",
                "status"        =>1,
                "created_at"        =>date('Y-m-d : H-i-s'),
        	],
        ];
        Product::insert($data);
		}
}